### PR TITLE
[Symfony] Skip $this arg on FormBuilderSetDataMapperRector

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7233

It only reproducible with:

- remove `stubs/Symfony/Component/Form` directory
- require --dev `symfony/form` in composer.json

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @FrancoisPog

**Comment by samsonasik** [comment]
it seems cause error in different rule test:

```diff
There was 1 failure:
1) Rector\Symfony\Tests\Rector\MethodCall\FormTypeInstanceToClassConstRector\FormTypeInstanceToClassConstRectorTest::test with data set #3 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Rector/MethodCall/FormTypeInstanceToClassConstRector/Fixture/form_add.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
         $builder->add('someText', \Rector\Symfony\Tests\Rector\MethodCall\FormTypeInstanceToClassConstRector\Fixture\SomeClass::class);
         $form = new TextType();
-        $form->add('text', \Rector\Symfony\Tests\Rector\MethodCall\FormTypeInstanceToClassConstRector\Source\AnotherFormTypeClass::class);
+        $form->add('text', new AnotherFormTypeClass());
```

**Comment by samsonasik** [comment]
I rolled back `stubs` directory and remove symfony/form from require-dev.

**Comment by samsonasik** [comment]
The test is now error again:

```diff

There was 1 failure:

1) Rector\Symfony\Tests\Rector\MethodCall\FormBuilderSetDataMapperRector\FormBuilderSetDataMapperRectorTest::test with data set #3 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Rector/MethodCall/FormBuilderSetDataMapperRector/Fixture/skip_correct_arg.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     public function run(FormConfigBuilderInterface $builder)
     {
         $propertyPathAccessor = new \Symfony\Component\Form\Extension\Core\DataAccessor\PropertyPathAccessor();
-        $builder->setDataMapper(new \Symfony\Component\Form\Extension\Core\DataMapper\DataMapper($propertyPathAccessor));
+        $builder->setDataMapper(new \Symfony\Component\Form\Extension\Core\DataMapper\DataMapper(new \Symfony\Component\Form\Extension\Core\DataAccessor\PropertyPathAccessor()));
     }
 }
 ```
 
 it seems the stubs need tweak or the rule need check against `$this` variable instead.

**Comment by samsonasik** [comment]
Fixed 🎉 with both check instanceof : 

- Symfony\Component\Form\DataMapperInterface
- Symfony\Component\Form\Extension\Core\DataMapper\DataMapper

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
