### PR TITLE
[Symfony] Skip SimplifyWebTestCaseAssertionsRector on no PHPUnit\Framework\TestCase class

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector-symfony/issues/123

### CODE REVIEW

**Comment by samsonasik** [comment]
@bocharsky-bw this should fix https://github.com/rectorphp/rector-symfony/issues/123

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review. 

I verified run it in https://github.com/bocharsky-bw/no-phpunit-rector-reproducer repository.

**Comment by TomasVotruba** [comment]
I'm not sure if this is correct, as the webtest case methods will not be changed. 
Instead we should provide somehow test case stub. 

Even better, the correct solution is adding the dependency, as Rector/PHPStan can work only with existing classes:
https://github.com/rectorphp/rector/issues/6531#issuecomment-870586660

**Comment by samsonasik** [comment]
@TomasVotruba Ok, I created alternative PR at https://github.com/rectorphp/rector-src/pull/1924

**Pull request closed without merging**
