### PR TITLE
[SYMFONY33] Fix configuration for the ArgumentAdderRector of the compile method of the ContainerBuilder (#327)

### PR DESCRIPTION
**Pull request by Tiefschwarz**
* Corrected the position of the argument that should be added
* Corrected the default value of the argument
* Set the name of the argument that is added
* Added unit test

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by rene-bos** [comment]
Hi @TomasVotruba, at [driftingly/rector-laravel](https://github.com/driftingly/rector-laravel) we have the same problem with the Rector job as this PR (`Error: 'fix/containerbuilder-compile-argument-adder-rector-configuration' branch not found.`). This can be seen in [this job run](https://github.com/driftingly/rector-laravel/actions/runs/4116130795/jobs/7105769970).

We use the same GitHub Actions configuration as here. Do you have a solution for this already? Maybe on some of the other Rector extension repositories? It is a bit diffucult for contributors to spot that they have to run both `vendor/bin/rector process` and after that `composer run fix-cs` when the Rector jobs fails on the `Run EndBug/add-and-commit` step..

**Comment by TomasVotruba** [comment]
Hi, we actually run Rector only for the core contributors. For the rest there is an issue with access as they're external contributors :)

This is the workflow we use on packages: https://github.com/rectorphp/reusable-workflows/blob/main/.github/workflows/rector.yaml

**Comment by TomasVotruba** [comment]
Here is the 2nd piece of puzzle, that checks the ownership: https://github.com/rectorphp/rector-symfony/blob/89e994ffb68921d571bbf5b8e1d59280b7f30a50/.github/workflows/code_analysis.yaml#L9-L18

**Comment by TomasVotruba** [comment]
For your case, add this workflow locally and tune it as needed. The reusable-workflows repository can change any time and is only for our internal packages.

**Pull request merged**
