### PR TITLE
 [CodeQuality] Add AddTraitGetterReturnTypeBasedOnSetterRequiredRector 

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba here the rule for our project for add getter return type by `@required` in settter in trait.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Could you add support for `#[\Symfony\Contracts\Service\Attribute\Required]` PHP 8 attribute as well?

**Comment by samsonasik** [comment]
sure, I added Required attribute support https://github.com/rectorphp/rector-symfony/pull/671/commits/93f3b6c7ffbf8595d15defe6e51ae917b5a9b6fd

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
