### PR TITLE
[Symfony] Skip remove comment deep statement on ConsoleExecuteReturnIntRector

### PR DESCRIPTION
**Pull request by samsonasik**
Based on https://getrector.org/demo/b6b66790-9939-49ba-ba4a-0f6bd3496e49, the comment should not be removed on deep ifs.

Fixes https://github.com/rectorphp/rector/issues/7668

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @escopecz

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by escopecz** [comment]
Thank you all! The community around Rector is amazing!

**Pull request merged**
