### PR TITLE
Add redirect response return support to ResponseReturnTypeControllerActionRector

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by johanadivare** [comment]
@TomasVotruba should we also add support for:
`JsonResponse` when we use `json` 
`BinaryFileResponse` when we use `file`
`StreamedResponse` when we use `stream`

**Comment by TomasVotruba** [comment]
@johanadivare Definitelly, that would be very useful :+1:  Could you handle that?

**Comment by johanadivare** [comment]
> @johanadivare Definitelly, that would be very useful +1 Could you handle that?

Will do :)

**Comment by TomasVotruba** [comment]
@johanadivare Thank you :bow:

**Comment by johanadivare** [comment]
See https://github.com/rectorphp/rector-symfony/pull/306

**Pull request merged**
