### PR TITLE
Fix bug with privatesCaller not found

### PR DESCRIPTION
**Pull request by PhilippSchreiber**
Fixes https://github.com/rectorphp/rector/issues/7613

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
@TomasVotruba The `MethodCallRenameWithArrayKey` error seems due to the class removed the `MethodCallRenameWithArrayKey` class on your PR:

-  https://github.com/rectorphp/rector-src/pull/3077

should the class and its usage be reverted ?

**Comment by samsonasik** [comment]
@TomasVotruba this got class `MethodCallRenameWithArrayKey` not found error;

https://github.com/rectorphp/rector-symfony/blob/695c960e7713438ef1077bebcbc6d298a95020d1/config/sets/symfony/symfony41.php#L44

**Comment by TomasVotruba** [comment]
@samsonasik That's intersting... it should fail on rector-src then. We probably need to run PHPStan in CI tests there too.
I'll revert, thanks

**Comment by TomasVotruba** [comment]
Thank you @PhilippSchreiber

**Pull request merged**
