### PR TITLE
Handle sprintf custom messages for asserts

### PR DESCRIPTION
**Pull request by JohJohan**
Todo handle all phpunit asserts that can have 'sprintf' function

### CODE REVIEW

**Comment by johanadivare** [comment]
We should handle `sprintf` when we refactor assertX(x sprintf('message'));

More info: https://github.com/rectorphp/rector-symfony/pull/314#issuecomment-1340810137 & https://github.com/rectorphp/rector-symfony/pull/314#issuecomment-1340859044

**Comment by samsonasik** [comment]
You may can use NodeTransformer to get extracted data, then next combine them as string value https://github.com/rectorphp/rector-src/blob/f35326d7010fa42458b44d3896b4791dcc22f78a/src/PhpParser/NodeTransformer.php

**Comment by johanadivare** [comment]
@samsonasik i added a check if function call and leave the argument as it is is that okay?

**Comment by johanadivare** [comment]
When i have latest composer package updates and run `vendor/bin/rector` i do not get any changes not sure why https://github.com/rectorphp/rector-symfony/actions/runs/3675860795/jobs/6215800640 is failing then

**Comment by samsonasik** [comment]
should be green after PR https://github.com/rectorphp/rector-symfony/pull/317 merged and you can rebase.

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
