### PR TITLE
Add list with anchors for all rules, update 72->73

### PR DESCRIPTION
**Pull request by sandoba**
Makes the growing collection of rules easier to use, similar to https://github.com/rectorphp/rector/edit/main/docs/rector_rules_overview.md.

### CODE REVIEW

**Comment by samsonasik** [comment]
The docs is generated by command:

```
composer docs
```

https://github.com/rectorphp/rector-symfony/blob/fd2b5dc1e2840ccd8edd8dab265053fb9f4ceba9/composer.json#L50

It should not be added manually.

**Comment by sandoba** [comment]
Well but isn't it supposed to be used by humans and should therefore be as easy to use as possible? If rules are added or removed in the future comparing the rector.php of a project with the current list would be much quicker.

And I've just submitted another pull request for "rectorphp/rector-doctrine" as well which had a duplicate listing for "TypedPropertyFromToOneRelationTypeRector". Not sure where that would come from is the generation is automated?

**Comment by samsonasik** [comment]
If there is a bug in docs generation, the command  need to be patched.

The docs is read from rector rules code sample 

https://github.com/rectorphp/rector-symfony/blob/fd2b5dc1e2840ccd8edd8dab265053fb9f4ceba9/src/Rector/BinaryOp/ResponseStatusCodeRector.php#L39

**Comment by johanadivare** [comment]
@samsonasik when i ran `composer docs` on master i saw some changes this is probably because i did it manually with https://github.com/rectorphp/rector-symfony/pull/261 shall i make another pull request with running `composer docs` for the project?

**Comment by samsonasik** [comment]
@johanadivare other PR is ok 👍 .

We basically should have weekly auto-generating PR like in `rector-src` for composer docs command

https://github.com/rectorphp/rector-src/blob/84361b82b630d31b49b009b46bdd3b1312ced2e8/.github/workflows/weekly_pull_requests.yaml#L22

but currently, autocommit consuming re-usable workflow not trigger CI on `rector-*` packages, see 

- https://github.com/rectorphp/rector-symfony/pull/121

we probably need to give `stefanzweifel/git-auto-commit-action` a try in the future, ref related feature request:

- https://github.com/rectorphp/rector/issues/7579

**Comment by TomasVotruba** [comment]
Closing as this is automated by `composer docs` run

**Pull request closed without merging**
