### PR TITLE
Add failing test fixture for `CommandPropertyToAttributeRector`

### PR DESCRIPTION
**Pull request by OskarStark**
# Failing Test for CommandPropertyToAttributeRector

Based on https://getrector.org/demo/144bbc1f-e170-45a9-b72f-d8daa0686db0

### CODE REVIEW

**Comment by samsonasik** [comment]
Could you try provide a patch for it? You can verify with PhpAttributeAnalyzer->hasPhpAttribute, ref
https://github.com/rectorphp/rector-src/blob/25dec6b32504d747ff62193ff4704144ca10b040/rules/Php80/NodeAnalyzer/PhpAttributeAnalyzer.php#L31

**Comment by johanadivare** [comment]
@OskarStark can you let us know if you will provide a patch otherwise someone else can pick it up

**Comment by OskarStark** [comment]
I am sorry, I cannot find time right now to fix this.

Christmas stress 🤪

**Comment by johanadivare** [comment]
> I am sorry, I cannot find time right now to fix this.
> 
> Christmas stress zany_face

Haha no worries then we know someone else can pick it up. Happy holidays already🎄

**Comment by johanadivare** [comment]
See https://github.com/rectorphp/rector-symfony/pull/312

**Comment by johanadivare** [comment]
I think this pull request can be closed as it will be fixed with https://github.com/rectorphp/rector-symfony/pull/312

**Comment by OskarStark** [comment]
You should add a `fix #312` in the PR Header of #312, then this PR gets closed when it will be merged.

**Pull request closed without merging**
