### PR TITLE
Avoid ContainerGetToConstructorInjectionRector on TestCase classes

### LINKED ISSUE #64: ContainerGetToConstructorInjectionRector should ignore PHPUnit or KernelTestCase classes
When having `ContainerGetToConstructorInjectionRector` activated it tries to refractor the PHPUnit KernelTestCase classes to constructor. But as this are not service this should be avoided.

I tried to contribute it but I found not yet a way how I can check in https://github.com/rectorphp/rector-symfony/blob/6f0f3d16e82f48e26690b9382dd015ad92bbf391/src/Rector/MethodCall/ContainerGetToConstructorInjectionRector.php#L77
if the `$node` is inside a PHPUnit TestCase class / KernelTestCase class.

### PR DESCRIPTION
**Pull request by alexander-schranz**
fixes #64

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you 👍 

We'll need a falling test case to be sure it won't be broken in the future

**Comment by alexander-schranz** [comment]
@TomasVotruba can you help me here. The `skip_test_case.php.inc` already exist but seems not be executed. All things I change there are just ignored and I'm not sure why.

**Comment by TomasVotruba** [comment]
In cases test passes without change, there is bug elsewhere.
Could you create a reproducible repository on Github with minimal failing code?

**Comment by alexander-schranz** [comment]
@TomasVotruba have a reproducable for my current open PRs: https://github.com/alexander-schranz/rector-reproducable-repository

**Comment by TomasVotruba** [comment]
Thanks, I can see it now :+1:

**Pull request closed without merging**
