### PR TITLE
feat: add web_profiler as config builder

### PR DESCRIPTION
**Pull request by dsdeboer**
While converting my Symfony configs I ran into [this issue](https://github.com/rectorphp/rector/issues/8705).

### CODE REVIEW

**Comment by dsdeboer** [comment]
Closing it, will commit it to the `rectorphp/rector-src` repository as requested

**Comment by TomasVotruba** [comment]
I think this is the right repository :+1:

**Comment by dsdeboer** [comment]
> I think this is the right repository 👍

Thanks @TomasVotruba, I've also opened up a PR to `rectorphp/vendor-patches`.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
