### PR TITLE
Add failing test fixture for WebTestCaseAssertResponseCodeRector

### PR DESCRIPTION
**Pull request by burkun-sergey**
# Failing Test for WebTestCaseAssertResponseCodeRector

Based on https://getrector.org/demo/ab75cc69-63b8-43d4-8069-5721ef30d979

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks :+1:  Could you provide a fix as well?

**Comment by johanadivare** [comment]
@burkun-sergey is this now fixed with https://github.com/rectorphp/rector-symfony/pull/267?

**Comment by burkun-sergey** [comment]
> @burkun-sergey is this now fixed with #267?

This is not fixed. (https://getrector.org/demo/1f189344-42cd-48fd-b1b9-3ae2d62f233f)

**Comment by burkun-sergey** [comment]
> Thanks +1 Could you provide a fix as well?

Sorry, have no time for that.

**Comment by johanadivare** [comment]
@burkun-sergey i created https://github.com/rectorphp/rector-symfony/pull/300 based from your branch, i changed a few things maybe you can check it out?

**Comment by johanadivare** [comment]
> @burkun-sergey i created #300 based from your branch, i changed a few things maybe you can check it out?

@burkun-sergey did you have time to take a look at my pull request?

**Comment by burkun-sergey** [comment]
> > @burkun-sergey i created #300 based from your branch, i changed a few things maybe you can check it out?
> 
> @burkun-sergey did you have time to take a look at my pull request?

I looked at the changes made by rector (dev-main branch). 

Correct changes made by rector:
```
$this->assertSame(HttpCode::FOUND, $client->getResponse()->getStatusCode(), 'Response to /');
// changed to
$this->assertResponseStatusCodeSame(HttpCode::FOUND, 'Response to /');
```
Incorrect changes:
```
$this->assertSame($expectedResponseCode, $client->getResponse()->getStatusCode(), sprintf('Response to %s', $uri));
// changed to
$this->assertResponseStatusCodeSame($expectedResponseCode, null);

$this->assertSame($location, $client->getResponse()->headers->get('Location'), 'Redirect to locale');
// changed to
$this->assertResponseRedirects($location, 'Redirect to locale');
```

**Comment by johanadivare** [comment]
```diff
-$this->assertSame($expectedResponseCode, $client->getResponse()->getStatusCode(), sprintf('Response to %s', $uri));
+$this->assertResponseStatusCodeSame($expectedResponseCode, sprintf('Response to %s', $uri));
```

```
-$this->assertSame($location, $client->getResponse()->headers->get('Location'), 'Redirect to locale');
+$this->assertResponseRedirects($location, 'Redirect to locale');
```

You expect this? can you create a test case for this, i agree with first case but second is correct in my option?

**Comment by johanadivare** [comment]
> ```diff
> assertResponseStatusCodeSame
> ```

Aha

I think it should be like:
```diff
-$this->assertSame('https://example.com', $response->headers->get('Location'), 'Custom message');
+$this->assertResponseRedirects('https://example.com', null, 'Custom message');
```
Because we didn't have the status code to check on right?

**Comment by johanadivare** [comment]
See https://github.com/rectorphp/rector-symfony/pull/314

**Pull request closed without merging**
