### PR TITLE
[CodeQuality] Skip posible return array + response on ResponseReturnTypeControllerActionRector

### PR DESCRIPTION
**Pull request by samsonasik**
ref https://github.com/rectorphp/rector-src/pull/6200#pullrequestreview-2207245293

it currently got incorrect return:

```diff
-    public function editAction(Request $request, $id = null)
+    public function editAction(Request $request, $id = null): ?array

Applied rules:
 * ResponseReturnTypeControllerActionRector
```

This PR fix it.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by samsonasik** [comment]
I found another many use cases that it got invalid `?array` if the `Response` return is from custom method non-native return, I will add only return when natively

**Comment by TomasVotruba** [comment]
Looks good :+1:

**Pull request merged**
