### PR TITLE
[WebTestCaseAssertResponseCodeRector] Correctly handle setting null

### PR DESCRIPTION
**Pull request by JohJohan**
Fixes #274

### CODE REVIEW

**Comment by johanadivare** [comment]
@burkun-sergey can you cr? If this fixes your cases?

**Comment by johanadivare** [comment]
@samsonasik do you know how i can get the value `sprintf('Custom message from url: %s', $url)`  right now `$this->valueResolver->getValue($args[2]->value, true)` returns `null`

**Comment by samsonasik** [comment]
No service to get sprintf value yet afaik, you may need to match extracted `%` values data. 

I think that can be in different PR for improvement.

**Comment by johanadivare** [comment]
> No service to get sprintf value yet afaik, you may need to match extracted `%` values data.
> 
> I think that can be in different PR for improvement.

I created separate pull request to fix that problem at a later point

**Comment by burkun-sergey** [comment]
> @burkun-sergey can you cr? If this fixes your cases?

I've tested this fix. It fixes only one of my two cases: change `$this->assertSame($location, $client->getResponse()->headers->get('Location'), 'Redirect to locale');` to `$this->assertResponseRedirects($location, null, 'Redirect to locale');`.

My second case with incorrect code change is still remains: change `$this->assertSame($expectedResponseCode, $client->getResponse()->getStatusCode(), sprintf('Response to %s', $uri));` to `$this->assertResponseStatusCodeSame($expectedResponseCode, null);`.

**Comment by johanadivare** [comment]
> > @burkun-sergey can you cr? If this fixes your cases?
> 
> I've tested this fix. It fixes only one of my two cases: change `$this->assertSame($location, $client->getResponse()->headers->get('Location'), 'Redirect to locale');` to `$this->assertResponseRedirects($location, null, 'Redirect to locale');`.
> 
> My second case with incorrect code change is still remains: change `$this->assertSame($expectedResponseCode, $client->getResponse()->getStatusCode(), sprintf('Response to %s', $uri));` to `$this->assertResponseStatusCodeSame($expectedResponseCode, null);`.

Correct that should be fixed with https://github.com/rectorphp/rector-symfony/pull/315

**Review by samsonasik — APPROVED** [review]
sprintf handling can be in separate PR, this part looks good 👍

**Comment by samsonasik** [comment]
Thank you @JohJohan

**Pull request merged**
