### PR TITLE
Add failing test fixture for WebTestCaseAssertResponseCodeRector

### PR DESCRIPTION
**Pull request by burkun-sergey**
# Failing Test for WebTestCaseAssertResponseCodeRector

Based on https://getrector.org/demo/6dcc081d-8237-4cc6-8c14-99fdf8cf33a9

### CODE REVIEW

**Comment by johanadivare** [comment]
@burkun-sergey is it correct that you can merge master in your branch and that your test fixture should work now as https://github.com/rectorphp/rector-symfony/pull/268 is merged?

**Comment by burkun-sergey** [comment]
> @burkun-sergey is it correct that you can merge master in your branch and that your test fixture should work now as #268 is merged?

I found error in tests/Rector/MethodCall/WebTestCaseAssertResponseCodeRector/Fixture/http_code.php.inc
There should be `$this->assertResponseStatusCodeSame($expectedHttpCode);` instead of `$this->assertResponseStatusCodeSame($expectedHttpCode, $response->getStatusCode());` on line 29

But anyway tests have failed (see https://github.com/rectorphp/rector-symfony/actions/runs/3385399166/jobs/5623497167).

**Comment by stefantalen** [comment]
@burkun-sergey if you apply the changes I commented, the test should pass 🙂. Can you update your PR?

**Comment by burkun-sergey** [comment]
> @burkun-sergey if you apply the changes I commented, the test should pass slightly_smiling_face. Can you update your PR?

I Updated my PR. Is it considered an error that unused variable `$response` has not been removed also?

**Comment by johanadivare** [comment]
@burkun-sergey i think rector doesn't cleanup these kind of unused variables maybe @samsonasik can confirm this for us.

**Comment by samsonasik** [comment]
unused variable assign is unrelated with this rule, so it is fine.

You can combine with dead code set list to remove that : 

```php
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
    // A. run whole set
    $rectorConfig->sets([
        // other set list here
        SetList::DEAD_CODE,
    ]);

    

 };

**Review by johanadivare — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Looks like Github Actions are stuck :thinking:

**Comment by johanadivare** [comment]
@burkun-sergey  maybe force push again?

**Comment by burkun-sergey** [comment]
> @burkun-sergey maybe force push?

I've made force push.

**Comment by stefantalen** [comment]
@TomasVotruba This can be merged 😉

**Review by johanadivare — APPROVED** [review]

**Review by stefantalen — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you 😊

**Pull request merged**
