### PR TITLE
 [SwiftMailer] Skip not instanceof Swift_Message on Swift_Message to email converter

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector-symfony/pull/604

### CODE REVIEW

**Comment by samsonasik** [comment]
@stefantalen I also rename underscored rule name to non-underscored for consistency

**Comment by stefantalen** [comment]
The same happens with other methods:

```diff
$mailing = new Mailing();
- $mailing->setSubject($request->request->get('mailing_subject'));
+  $mailing->subject($request->request->get('mailing_subject'));
```

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by stefantalen** [comment]
Nice work 🥳

**Pull request merged**
