### PR TITLE
 [Dep] Update requirement to PHP 8.1 

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
it seems re-usable workflow needs update

rectorphp/reusable-workflows/.github/workflows/code_analysis.yaml@main

**Comment by samsonasik** [comment]
Close-reopen to restart build.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
