### PR TITLE
[Symfony 4.4] Updating AuthorizationCheckerIsGrantedExtractorRector

### PR DESCRIPTION
**Pull request by stefantalen**
Felt like this rule was missing the AbstractController implementation.

This PR will add `AbstractController::isGranted()` ~and `AbstractController::denyAccessUnlessGranted()`~ support

### CODE REVIEW

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Looks good, ready to merge?

**Comment by stefantalen** [comment]
Hold your horses 😬  I need to work on the `denyUnlessGranted()` implementation

**Comment by stefantalen** [comment]
I'm looking for the right return type to get from a `MethodCall`
```php
$this->denyAccessUnlessGranted(['ROLE_USER', 'ROLE_ADMIN']);
```
To 
```php
$this->denyAccessUnlessGranted('ROLE_USER');
$this->denyAccessUnlessGranted('ROLE_ADMIN');
```
Using the current `processExtractIsGranted`, the result is
```php
$this->denyAccessUnlessGranted('ROLE_USER') || $this->denyAccessUnlessGranted('ROLE_ADMIN');
```
So I was thinking on replacing the `BooleanOr` for something else, but am kind of lost 😨

**Comment by stefantalen** [comment]
Decided to drop working on the `AbstractController::denyUnlessGranted` refactoring, it'll probably need a different rule or the `getNodeTypes` should be `ClassMethod` instead of `MethodCall` so I can traverse the nodes.

Anyhow, the update for `AbstractController::isGranted` is included in this PR 🙂

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Let's give it a try, thank you @stefantalen

**Pull request merged**
