### PR TITLE
Move FormTypeWithDependencyToOptionsRector to Symfony 3.0 set

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by W0rma** [comment]
@TomasVotruba What's the motivation behind this change?

Since https://github.com/symfony/symfony-docs/commit/ac08120d4985b9647e319f5b10b1cb2cb248391e#diff-3f7adba991201416ba5b300423ce923540a4374c6b5e7fa3ff128a2055bf28b0 even the symfony docs recommend using dependency injection.

**Comment by TomasVotruba** [comment]
I see. Here is it depends whether the object is a dependency service or value object.

Could you add a test fixture that fails for service?

**Comment by W0rma** [comment]
I have added a test case in https://github.com/rectorphp/rector-symfony/pull/488

**Comment by bobvandevijver** [comment]
This was already discussed before in #180, #184 and fixed with #189. The FormTypeWithDependencyToOptionsRector should be a one-time use for people who want to use it, so I am quite surprised to see it has now been readded to the Symfony set.

**Comment by TomasVotruba** [comment]
@bobvandevijver Thanks for joining in :+1: my bad and appologies for caused trouble.s

I wonder if the rule should even exist, if it always require a developers attention and careful consideration of change.
I think it would be better to remove it to avoid similar issues like you've reffered.

**Pull request merged**
